# root directory
rootDir: 'ass_test'
# sub directories
subDirs:
  -
    name: 'documents'
    desc: 'All kinds of files'
  -
    name: 'videos'
    desc: 'Video type files'
  -
    name: 'audios'
    desc: 'Audio type files'